base: 'https://publicplan.ddev.site'
baseVariants:
  -
    base: 'https://publicplan.de'
    condition: 'applicationContext == "Production"'
  -
    base: 'https://beta.publicplan.de'
    condition: 'applicationContext == "Production/Beta"'
  -
    base: 'https://staging.publicplan.de/'
    condition: 'applicationContext == "Production/Staging"'
  -
    base: 'https://publicplan.ddev.site'
    condition: 'applicationContext == "Development"'
languages:
  -
    title: English
    enabled: true
    languageId: 0
    base: /
    locale: en_US.UTF-8
    navigationTitle: English
    flag: us
rootPageId: 1
websiteTitle: 'Publicplan GmbH'
